function y = chebyshev2(x, Fstop1, Fpass1, Fpass2, Fstop2)
%CHEBYSHEV2 Filters input x and returns output y.

%Inputs:
%Signal to be filtered
 % First Stopband Frequency
% First Passband Frequency
 % Second Passband Frequency
% Second Stopband Frequency

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 04-Jul-2018 21:57:46

persistent Hd;

if isempty(Hd)
    Astop1 = 60;     % First Stopband Attenuation (dB)
    Apass  = 1;      % Passband Ripple (dB)
    Astop2 = 60;     % Second Stopband Attenuation (dB)
    Fs     = 16000;  % Sampling Frequency
    
    h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
        Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    
    Hd = design(h, 'cheby2', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


