function y = elliptic(x, Fstop1, Fpass1, Fpass2, Fstop2)
%ELLIPTIC Filters input x and returns output y.
%Inputs: signal to be filtered, frequency at the first stop band, frequency at the first pass band
%frequency at the second pass band, frequency at the second stop band.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 04-Jul-2018 21:51:10

persistent Hd;

if isempty(Hd)
   
    Astop1 = 60;     % First Stopband Attenuation (dB)
    Apass  = 1;      % Passband Ripple (dB)
    Astop2 = 60;     % Second Stopband Attenuation (dB)
    Fs     = 16000;  % Sampling Frequency
    
    h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
        Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    
    Hd = design(h, 'ellip', ...
        'MatchExactly', 'both', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


