function Hd = getEquirippleFilter(pass1, pass2)
%GETFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 07-Jul-2018 16:23:14

Fstop1 = pass1 - 60;    % First Stopband Frequency
Fpass1 = pass1;  % First Passband Frequency
Fpass2 = pass2;  % Second Passband Frequency
Fstop2 = pass2 + 60;    % Second Stopband Frequency
Astop1 = 60;      % First Stopband Attenuation (dB)
Apass  = 1;       % Passband Ripple (dB)
Astop2 = 60;      % Second Stopband Attenuation (dB)
Fs     = 16000;   % Sampling Frequency

h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);

Hd = design(h, 'equiripple', ...
    'MinOrder', 'any');


